---
name: Rust
'on':
  - push
  - pull_request
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
      - name: Rustfmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy -- -D warnings
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: '--security-opt seccomp=unconfined'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cargo install cargo-tarpaulin
      - name: Generate code coverage
        run: cargo tarpaulin --ignore-tests --verbose --workspace